_BASE_: Base-ADE20K-150.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "DeformableHead"
    PIXEL_DECODER_NAME: "DeformableTransformerEncoderPixelDecoder"
    IN_FEATURES: ["res3", "res4", "res5"] #["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 150
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "transformer_encoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 300
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 1024
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    PRE_NORM: False
    DEFORMABLE_PREDICTOR: True

TEST:
  EVAL_PERIOD: 4000