_BASE_: Base-ADE20K-150.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "EntityMaskFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
    MATCHER: "EntityHungarianMatcher"
    ENTITY: True
    ENTITY_WEIGHT: 1.0
    IS_PRETRAIN_DATASET: True
    TEST:
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.7
INPUT:
  DATASET_MAPPER_NAME: "mask_former_panoptic"
DATASETS:
  TRAIN: ("coco_2017_train_panoptic",)
  TEST: ("coco_2017_val_panoptic",)
TEST:
  EVAL_PERIOD: 0  # no inference
SOLVER:
  MAX_ITER: 180000