_BASE_: Base-ADE20K-150.yaml
MODEL:
  BACKBONE:
    FREEZE_AT: 5
  META_ARCHITECTURE: "MaskFormer_seperate"
  SEM_SEG_HEAD:
    NAME: "MaskClsFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 150
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
    FREEZE: True
    CLS_HEAD_DIM: 256
    CLS_HEAD_LAYERS: 4
SOLVER:
  BASE_LR: 0.01
  MAX_ITER: 160000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "SGD"
