_BASE_: Base-ADE20K-150.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_classification_backbone"
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: None
    NORM: "SyncBN"

  META_ARCHITECTURE: "MaskedClassification"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 150
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
    ENTITY: True
#    USE_PRED_LOSS: True
#    TEST:
#      ENTITY_ON: True
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval [ "[int(x * 0.1 * 512) for x in range(5, 21)]" ]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
  DATASET_MAPPER_NAME: "mask_former_multi_cls"
  SIZE_DIVISIBILITY: -1
  CROP:
    ENABLED: False

SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.01
#  STEPS: (50000,100000)
  MAX_ITER: 150000 # ~3000 iter per epoch
  WARMUP_FACTOR: 0.00033
  WARMUP_ITERS: 3000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "SGD"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: False


DATASETS:
  TRAIN: ("ade20k_multi_cls_train",)
  TEST: ("ade20k_multi_cls_val",)