_BASE_: Base-ADE20K-150.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_v1c_backbone"
    FREEZE_AT: 5
  RESNETS:
    NORM: "BN"
  META_ARCHITECTURE: "MaskedClassification_v2"
  SEM_SEG_HEAD:
    PIXEL_DECODER_NAME: "ClsDecoder"
    NAME: "MaskedClsHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 150
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
    ENTITY: True
#    USE_PRED_LOSS: True
#    TEST:
#      ENTITY_ON: True
INPUT:
  SIZE_DIVISIBILITY: -1

SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.01
#  STEPS: (50000,100000)
  MAX_ITER: 15000 # 165k annotations
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "SGD"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: False
  CHECKPOINT_PERIOD: 2000

DATALOADER:
  NUM_WORKERS: 16

DATASETS:
  TRAIN: ("ade20k_sem_seg_train",)
  TEST: ("ade20k_sem_seg_val",)